# Generated by Django 4.2 on 2023-04-07 19:07

from django.db import migrations, models
import django.db.models.deletion
import menu.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Слаг')),
            ],
            options={
                'verbose_name_plural': 'Mеню',
                'db_table': 'app_menu',
                'ordering': ['id'],
            },
            bases=(menu.utils.ModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='Слаг')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='menu.menu')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='menu.menuitem')),
            ],
            options={
                'verbose_name_plural': 'Пункты меню',
                'db_table': 'app_menu_item',
                'ordering': ['id'],
            },
            bases=(menu.utils.ModelMixin, models.Model),
        ),
    ]
